### ISSUE TITLE
Packaging issue with Debain 8.1

### ISSUE THREAD

**Issue by ovaistariq** [twindb/twindb-agent#6] opened 2015-08-23 20:46 UTC
STDOUT: make[1]: Entering directory '/tmp/twindb-agent'
       Checking dependencies
       build-essential ... installed
       devscripts ... installed
       debhelper ... installed
       rm -fr build/
       rm -fr dist/
       rm -fr .eggs/
       find . -name '*.egg-info' -exec rm -fr {} +
       find . -name '*.egg' -exec rm -f {} +
       find . -name '*.pyc' -exec rm -f {} +
       find . -name '*.pyo' -exec rm -f {} +
       find . -name '*~' -exec rm -f {} +
       find . -name '__pycache__' -exec rm -fr {} +
       rm -fr .tox/
       rm -f .coverage
       rm -fr htmlcov/
       python setup.py sdist
       running sdist
       running check
       reading manifest template 'MANIFEST.in'
       writing manifest file 'MANIFEST'
       creating twindb-agent-0.2.0
       creating twindb-agent-0.2.0/docs
       creating twindb-agent-0.2.0/scripts
       creating twindb-agent-0.2.0/support
       creating twindb-agent-0.2.0/tests
       creating twindb-agent-0.2.0/twindb_agent
       creating twindb-agent-0.2.0/twindb_agent/job_type
       copying files to twindb-agent-0.2.0...
       copying AUTHORS.rst -> twindb-agent-0.2.0
       copying CONTRIBUTING.rst -> twindb-agent-0.2.0
       copying HISTORY.rst -> twindb-agent-0.2.0
       copying LICENSE -> twindb-agent-0.2.0
       copying Makefile -> twindb-agent-0.2.0
       copying README.rst -> twindb-agent-0.2.0
       copying setup.cfg -> twindb-agent-0.2.0
       copying setup.py -> twindb-agent-0.2.0
       copying docs/Makefile -> twindb-agent-0.2.0/docs
       copying docs/authors.rst -> twindb-agent-0.2.0/docs
       copying docs/conf.py -> twindb-agent-0.2.0/docs
       copying docs/contributing.rst -> twindb-agent-0.2.0/docs
       copying docs/history.rst -> twindb-agent-0.2.0/docs
       copying docs/index.rst -> twindb-agent-0.2.0/docs
       copying docs/installation.rst -> twindb-agent-0.2.0/docs
       copying docs/make.bat -> twindb-agent-0.2.0/docs
       copying docs/readme.rst -> twindb-agent-0.2.0/docs
       copying docs/usage.rst -> twindb-agent-0.2.0/docs
       copying scripts/twindb-agent -> twindb-agent-0.2.0/scripts
       copying support/twindb-agent -> twindb-agent-0.2.0/support
       copying support/twindb-agent.logrotate -> twindb-agent-0.2.0/support
       copying support/twindb-agent.man -> twindb-agent-0.2.0/support
       copying tests/__init__.py -> twindb-agent-0.2.0/tests
       copying tests/test_twindb_agent.py -> twindb-agent-0.2.0/tests
       copying twindb_agent/__about__.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/__init__.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/__main__.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/agent.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/api.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/config.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/globals.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/gpg.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/handlers.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/httpclient.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/job.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/log.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/twindb_mysql.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/utils.py -> twindb-agent-0.2.0/twindb_agent
       copying twindb_agent/job_type/__init__.py -> twindb-agent-0.2.0/twindb_agent/job_type
       copying twindb_agent/job_type/backup.py -> twindb-agent-0.2.0/twindb_agent/job_type
       copying twindb_agent/job_type/restore.py -> twindb-agent-0.2.0/twindb_agent/job_type
       copying twindb_agent/job_type/send_key.py -> twindb-agent-0.2.0/twindb_agent/job_type
       creating dist
       Creating tar archive
       removing 'twindb-agent-0.2.0' (and everything under it)
       # python setup.py bdist_wheel
       ls -l dist
       total 40
       -rw-r--r-- 1 root root 39280 Aug 23 07:04 twindb-agent-0.2.0.tar.gz
       Generating changelog
       mkdir -p "build"
       cp "dist/twindb-agent-0.2.0.tar.gz" "build/twindb-agent_0.2.0.orig.tar.gz"
       tar zxf "build/twindb-agent_0.2.0.orig.tar.gz" -C "build"
       cp -LR support/deb/debian/ "build/twindb-agent-0.2.0"
       cd "build/twindb-agent-0.2.0" && debuild -us -uc
        dpkg-buildpackage -rfakeroot -D -us -uc
       dpkg-buildpackage: warning: using a gain-root-command while being root
       dpkg-buildpackage: source package twindb-agent
       dpkg-buildpackage: source version 0.2.0-1.jessie
       dpkg-buildpackage: source distribution jessie
       dpkg-buildpackage: source changed by TwinDB Packager (TwinDB packager key) <packager@twindb.com>
        dpkg-source --before-build twindb-agent-0.2.0
       dpkg-buildpackage: host architecture amd64
        fakeroot debian/rules clean
       debian/rules:11: *** missing separator.  Stop.
       rror: fakeroot debian/rules clean gave error exit status 2
       Makefile:148: recipe for target 'build-deb' failed
       make[1]: Leaving directory '/tmp/twindb-agent'
       Makefile:94: recipe for target 'package' failed
       STDERR: /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
         warnings.warn(msg)
       /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
         warnings.warn(msg)
       /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
         warnings.warn(msg)
       /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
         warnings.warn(msg)
       /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
         warnings.warn(msg)
       warning: sdist: standard file not found: should have one of README, README.txt
       
       warning: no previously-included files matching '__pycache__' found under directory '*'
       warning: no previously-included files matching '*.py[co]' found under directory '*'
       dch warning: Recognised distributions are: unstable, testing, stable,
       oldstable, experimental, {testing-,stable-,oldstable-,}proposed-updates,
       {testing,stable,oldstable}-security, wheezy-backports, jessie-backports and UNRELEASED.
       Using your request anyway.
       dch: Did you see that warning?  Press RETURN to continue...
       debuild: fatal error at line 1376:
       dpkg-buildpackage -rfakeroot -D -us -uc failed
       make[1]: *** [build-deb] Error 29
       make: *** [package] Error 2

**Comment by akuzminsky** [comment] 2015-08-23 22:58
Duplicate of issue #5

**Closed** 2015-08-23 22:58 UTC
Labels: bug, duplicate
